settings: # some file locations
    file-locations:
        GENOME: /home/haliupenguin/.local/share/genomes/hg38/hg38.fa
        INTERSECT: ./data/intersect_file.bed
        DICTIONARY: /home/haliupenguin/.local/share/genomes/hg38/hg38.dict
        SIZES: ./data/hg38.chrom.sizes
        BED_SIZE: ./data/human-hg18-size.bed
        GENE_BED: ./data/hg38_RefSeq.bed.gz
        EXBAM: ./data/toy.bam
        BAZAMBAM: ./data/bazam.bam
        FASTA: ./data/toy.fa
        CHAIN: ./data/hg38ToHg19.over.chain.gz
        BIGWIG: ./data/toy.bw
        DESIGN: ./data/example.design
        GTF: ./data/toy.gtf
        SLNCKY_CONFIG: ./data/annotations.config
        2BIT: ./data/toy.2bit
        LOGIT: ./data/logit.logit.RData
        HEXAMER: ./data/hexamer_tab.tsv
        CONTACT_MATRIX: ./data/contact_frequency_matrix.gz
        BGT: ./data/1kg11-1M.bgt
        OUTPUT_DIR: ./scratch/trash
tools:  # Require that the command line sequence to be executed be written on one line
    - alfred:
        annotate: alfred annotate -b GENE_BED FILE
    - alignstats:
        alignstats: alignstats -i EXBAM -o /dev/stdout -t FILE
    - atactk:
        make_cut_matrix: make_cut_matrix -a -b '(36-149 150-324 325-400 1)' EXBAM FILE
    - ataqv:
        ataqv: ataqv --peak-file FILE --metrics-file /dev/null human EXBAM
    - augur:
        mask: augur mask -s VCF --mask FILE -o /dev/stdout
    - bazam:
        bazam: bazam -bam BAZAMBAM -L FILE
    - bedops:
        intersect: bedops --intersect INTERSECT FILE
        complement: bedops --complement INTERSECT FILE
        element-of: bedops --element-of 10 INTERSECT FILE
        error checking: bedops -ec --everything FILE
    - bedtools:
        intersect: bedtools intersect -a INTERSECT -b FILE
        merge: sort -k1,1 -k2,2n FILE > TEMP1; bedtools merge -i TEMP1
        coverage: bedtools coverage -a INTERSECT -b FILE
    - bgt:
        view: bgt view -B FILE BGT
    - bioconvert:
        bed2wiggle: bioconvert bed2wiggle FILE /dev/stdout --force
    - bioFluff:
        heatmap: fluff heatmap -f FILE -d EXBAM -o OUTPUT_DIR/
    - biopet:
        WipeReads: biopet tool WipeReads -I EXBAM -r FILE -o /dev/stdout 2>/dev/null
    - blockbuster:
        blockbuster: blockbuster.x FILE
    - cgat:
        merge: cat FILE | cgat bed2bed --method=merge
        shift: chat FILE | cgat bed2bed --method=offset -g GENOME
        bed2stats: cgat bed2table < FILE
    - chunked-scatter:
        chunked-scatter: chunked-scatter -p OUTPUT_DIR/scatter_ -i FILE -m 10 -c 40
    - cistrome-beta:
        minus: BETA minus -p FILE -g hg19
    - cnvkit:
        target: cnvkit.py target FILE
        access: cnvkit.py access GENOME -x FILE
    - combined p-values:
        acf: comb-p FILE
    - concoct:
        cut_up_fasta: cut_up_fasta.py -c 5 -o 0 -m -b FILE FASTA
        coverage_table: converage_table.py FILE EXBAM
    - cpat:
        cpat: cpat.py -r GENOME -g FILE -d LOGIT -x HEXAMER -o OUTPUT_DIR/cpat
    - crossmap:
        CrossMap: CrossMap.py bed CHAIN FILE
    - dammet:
        DamMet: DamMet -b EXBAM -r GENOME -c chr19 -e FILE
    - deeptools:
        computeMatrix scale-regions: computeMatrix scale-regions -S BIGWIG -R FILE -bs 1 -o OUTPUT_DIR/computeMatrixResult
    - dsh-bio:
        filter-bed: dsh-bio filter-bed -i FILE
    - elprep:
        bed-to-elsites: elprep bed-to-elsites FILE /dev/stdout 2>/dev/null
    - epic2:
        epic: epic2 --treatment FILE
    - fithic:
        HiCPro2FitHiC: scratch/fithic/fithic/utils/HiCPro2HitFiC.py -i CONTACT_MATRIX -b FILE
    - f-seq:
        f-seq: scratch/F-seq/dist~/fseq/bin/fseq -f 10 -o OUTPUT_DIR -of bed FILE
    - gat:
        gat: scratch/gat/scripts/gat-run.py --segment-file=FILE --annotation-file=INTERSECT --workspace-file=BED_SIZE
    - genometools:
        bed_to_gff: gt bed_to_gff3 FILE
    - gff-compare:
        trmap: trmap INTERSECT FILE
    # - gimmemotifs:
    #     motifs: gimme motifs FILE -g hg38 -n scratch/gimme
    #     scan: gimme scan FILE -g hg38 -c 0 -n 1 -b'
    - HipSTR:
        HipSTR: scratch/HipSTR/HipSTR --bams BAZAMBAM --fasta GENOME --regions FILE --str-vcf OUTPUT_DIR/hipstr.vcf.gz
    - homer:
        findMotifsGenome: findMotifsGenome.pl FILE hg19 OUTPUT_DIR -size 20
    - iCount:
        clusters: iCount clusters INTERSECT FILE OUTPUT_DIR/iCount.txt
        annotate: iCount annotate GTF FILE OUTPUT_DIR/iCount.bed
    # - idr:
    #     idr: idr --samples INTERSECT FILE --input-file-type bed --rank score    
    - igvtools:
        count: igvtools count FILE stdout hg18
        sort: igvtools sort FILE stdout
    - intervene:
        upset: intervene upset -i FILE INTERSECT -o OUTPUT_DIR/
        venn: intervene venn -i FILE INTERSECT -o OUTPUT_DIR/
    - macs2:
        callpeak: macs2 callpeak -t FILE -f BED 
    - mosdepth:
        mosdepth: mosdepth -b FILE OUTPUT_DIR/mos EXBAM
    - multigps:
        multigps: sed 's+REP1+INTERSECT+g' DESIGN | sed 's+REP2+FILE+g' > TEMP1; multigps -Xmx4G --geninfo SIZES --design TEMP1 -r 1 --out OUTPUT_DIR/
    - nanosv:
        nanosv: NanoSV -b FILE BAZAMBAM
    - ngs-bits:
        BedAdd: BedAdd -in INTERSECT FILE
        BedChunk: BedChunk -n 10 -in FILE
        BedExtend: BedExtend -n 100 -in FILE
        BedMerge: BedMerge -in FILE
    - ngsutils:
        reduce: bedutils reduce FILE
        stats: bedutils stats FILE
        extend: bedutils extend -5 10 FILE
    - novasplice:
        novasplice: novasplice -v VCF -r GENOME -b FILE -c SIZES
    - octopus:
        octopus: octopus -R FASTA -I EXBAM -t FILE
    - peakranger:
        ccat: peakranger ccat --format bed FILE INTERSECT --output /dev/stdout
    - Piranha:
        basic: Piranha FILE
    - peakzilla:
        peakzilla: peakzilla.py FILE INTERSECT
    - picard:
        BedToIntervalList: picard BedToIntervalList INPUT=FILE SD=DICTIONARY OUTPUT=/dev/stdout
    - plastid:
        reformat_transcripts: reformat_transcripts --annotation_files FILE --annotation_format BED /dev/stdout
        findjuncs: findjuncs OUTPUT_DIR/result --annotation_format BED --annotation_files FILE
    - portcullis:
        compare: junctools compare INTERSECT FILE
    - preseq:
        c_curve: preseq c_curve FILE
    - pygtftk:
        bed_to_gtf: gtftk bed_to_gtf -i FILE
    - qualimap:
        comp-counts: qualimap comp-counts -bam EXBAM -gtf FILE
    - quast:
        quast: quast FASTA --min-contig 5 -g FILE
    - rapid:
        rapidStats: rapidStats.sh -o=OUTPUT_DIR/ -f=EXBAM -ft=BAM -a=FILE
    - regtools:
        junctions annotate: regtools junctions annotate FILE GENOME GTF -S
    - rpkmforgenes:
        rpkmforgenes: rpkmforgenes.py -o OUTPUT_DIR/rpkm.txt -i INTERSECT -a FILE
    - rseg:
        rseg: rseg -c BED_SIZE -o /dev/stdout FILE
    - rseqc:
        geneBody_coverage: geneBody_coverage.py -i EXBAM -r FILE -o OUTPUT_DIR/geneBody
    - samtools:
        bedcov: samtools bedcov FILE EXBAM
    - segtools:
        overlap: segtools-overlap INTERSECT FILE
    - seqkit:
        subseq: seqkit subseq --bed FILE FASTA
        seq: seqkit seq -M FILE FASTA
    - seqtk:
        subseq: seqtk subseq FASTA FILE
    - slncky:
        slncky: slncky FILE hg38 OUTPUT_DIR/ -c SLNCKY_CONFIG
    - smoove:
        call: smoove call -x --name tester --exclude FILE --fasta FASTA BAM -o OUTPUT_DIR/
    - snpEff:
        count: snpEff count hg38 INTERSECT FILE -Xmx4g
    - snpSift:
        join: SnpSift join -cols1 bed -cols2 bed INTERSECT FILE -Xmx2g
        intersect: SnpSift intersect INTERSECT FILE -Xmx2g
    - tobias:
        ATACorrect: TOBIAS ATACorrect --bam EXBAM --genome FASTA --peaks FILE
    - twobitreader:
        twobitreader: python -m twobitreader 2BIT < FILE
    - ucsc:
        bedSort: ./ucsc-apps/bedSort FILE /dev/stdout
        bedClip: ./ucsc-apps/bedClip FILE SIZES /dev/stdout
        bedRemoveOverlap: ./ucsc-apps/bedRemoveOverlap FILE /dev/stdout
    - variantbam:
        variant: variant EXBAM -l FILE
    - vcflib:
        annotate: vcfannotate -b FILE VCF
        intersect: vcfintersect -b FILE VCF
    - wiggletools:
        AUC: wiggletools AUC FILE
    - wisestork:
        gc-correct: wisestork gc-correct -R GENOME -I FILE
    - xyalign:
        PREPARE_REFERENCE: xyalign --PREPARE_REFERENCE --ref GENOME --reference_mask FILE -o OUTPUT_DIR/ --x_chromosome chrX --y_chromosome chrY
python-versions:
    alfred: 3.7
    alignstats: 3.7
    atactk: 2.7
    ataqv: 2.7
    augur: -1.0  # Installed on "augur" conda environment
    bazam: 3.7
    bcftools: 3.7
    bedops: 3.7
    bedtools: 3.7
    bgt: 3.7
    bioconvert: 3.6
    bioFluff: 3.6
    biopet: 3.7
    blockbuster: 3.7
    cgat: 3.6
    chunked-scatter: 3.6
    cistrome-beta: 2.7
    cnvkit: 3.6
    combined p-values: 2.7
    concoct: 3.6
    cpat: 2.7
    crossmap: 3.6
    dammet: 3.7
    deeptools: 3.7
    dsh-bio: 3.7
    elprep: 3.7
    epic2: 3.7
    fithic: 3.6
    f-seq: 3.6
    gat: 2.7
    genometools: 2.7
    gff-compare: 3.7
    gimmemotifs: 3.6
    HipSTR: 3.7 
    homer: 3.6
    iCount: 3.6
    idr: 3.6
    igvtools: 3.7
    intervene: 3.7
    macs2: 2.7
    mosdepth: 3.7
    multigps: 3.6
    nanosv: 3.6
    ngs-bits: 3.7
    ngsutils: 2.7
    novasplice: 3.6
    peakranger: 3.6
    peakzilla: 2.7
    picard: 3.6
    Piranha: 2.7
    plastid: 2.7
    portcullis: 3.6
    preseq: -1.0
    pygtftk: 3.6
    octopus: 2.7
    qualimap: 3.7
    quast: 3.6
    rapid: 3.7
    regtools: 3.7
    rpkmforgenes: 2.7
    rseg: 3.7
    rseqc: 3.7
    samtools: 3.7
    segtools: 2.7
    seqkit: 3.7
    seqtk: 3.7
    slncky: 2.7
    smoove: 2.7
    snpEff: 3.7
    snpSift: 3.6
    tobias: 3.7
    twobitreader: 3.7
    ucsc: 3.7
    variantbam: 3.7
    vcflib: 3.7
    wiggletools: 3.7
    wisestork: 3.7
    xyalign: 2.7
