settings:
    hidden: 0
tools:
    - bedTools:
        intersect: bedtools intersect -a ./intersect_file.bed -b FILE
        merge: sort -k1,1 -k2,2n FILE > ./temp.bed; bedtools merge -i ./temp.bed
        coverage: bedtools coverage -a ./intersect_file.bed -b FILE
waste:
    - ./temp.bed